import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion} from 'framer-motion';
import {Music,Volume2,ArrowRight,RotateCcw,X,Heart,Star,Sparkles} from 'lucide-react';
import './styles.css';
import config from './config/birthdayConfig';

const stages=['intro','message','candles','cake','memories','wishes','letter','final'];
const fade={initial:{opacity:0,scale:1.03,filter:'blur(4px)'},animate:{opacity:1,scale:1,filter:'blur(0px)'},exit:{opacity:0,scale:.97,filter:'blur(4px)'}};

function Particles({celebrate=false}){const items=Array.from({length:celebrate?32:16},(_,i)=>i); return <div className="particles" aria-hidden="true">{items.map(i=><motion.span key={i} className={i%4===0?'heart-p':i%4===1?'star-p':'dot-p'} initial={{x:`${(i*47)%100}vw`,y:'105vh',opacity:0,rotate:i*17}} animate={{y:'-10vh',opacity:[0,.18,.1,0],rotate:i*17+80}} transition={{duration:10+(i%6)*2,delay:(i%7)*.7,repeat:Infinity,ease:'linear'}}>{i%4===0?'♥':i%4===1?'✦':'·'}</motion.span>)}</div>}
function Progress({stage}){const idx=stages.indexOf(stage); return <div className="progress" aria-label={`Step ${idx+1} of ${stages.length}`}>{stages.map((s,i)=><span key={s} className={i<=idx?'active':''}/>)}</div>}
function Button({children,onClick,disabled=false,secondary=false}){return <motion.button whileHover={{scale:1.035}} whileTap={{scale:.96}} className={`primary ${secondary?'secondary':''}`} onClick={onClick} disabled={disabled}>{children}</motion.button>}
function MusicToggle({playing,setPlaying,audio}){return <button className="music" aria-label={playing?'Pause music':'Play music'} onClick={()=>{if(!audio.current)return;if(playing){audio.current.pause();setPlaying(false)}else{audio.current.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))}}}>{playing?<Volume2 size={19}/>:<Music size={19}/>} {playing&&<span className="waves"><i/><i/><i/></span>}</button>}
function Intro({next,startMusic}){return <motion.section className="stage" {...fade}><div className="orb orb-a"/><div className="orb orb-b"/><div className="glass intro-card"><span className="eyebrow">{config.intro.eyebrow}</span><h1>{config.intro.title.replace('BIRTHDAY_NAME',config.birthdayName)}</h1><p>{config.intro.description}</p><Button onClick={()=>{startMusic();next()}}>Open the surprise <span>✦</span></Button><div className="tiny-note">made for {config.relationship.toLowerCase()}</div></div></motion.section>}
function Message({next}){return <motion.section className="stage" {...fade}><div className="paper-card"><span className="script">FOR YOU ♡</span><h2>{config.message.title}</h2><div className="heart-mark"><Heart fill="currentColor" size={25}/></div><p>{config.message.text}</p><Button onClick={next}>Keep going <ArrowRight size={18}/></Button></div></motion.section>}
function Candle({lit,onClick,n}){return <button className={`candle-wrap ${lit?'lit':''}`} onClick={onClick} aria-label={`Candle ${n}, ${lit?'lit':'unlit'}`}><span className="num">{n}</span><span className="flame">✦</span><span className="candle-body"/></button>}
function Cake({candles,onCandle,cuttable,onCut}){return <div className={`cake-scene ${cuttable?'ready':''}`}><div className="cake-glow"/><div className="candles"><Candle n={1} lit={candles[0]} onClick={()=>onCandle(0)}/><Candle n={2} lit={candles[1]} onClick={()=>onCandle(1)}/><Candle n={3} lit={candles[2]} onClick={()=>onCandle(2)}/></div><button className="cake" disabled={!cuttable} onClick={onCut} aria-label={cuttable?'Tap cake to cut':'Light all candles first'}><div className="cake-top"><span/><span/><span/></div><div className="icing"><i/><i/><i/></div><div className="layer upper"/><div className="cream-line"/><div className="layer lower"/><div className="plate"/></button></div>}
function Candles({candles,setCandles,next}){const all=candles.every(Boolean);return <motion.section className="stage" {...fade}><span className="eyebrow">A LITTLE RITUAL</span><h2>{config.cake.title}</h2><p className="sub">{all?'Make a wish... ✨':config.cake.subtitle}</p><Cake candles={candles} onCandle={i=>setCandles(a=>a.map((v,j)=>j===i?true:v))} cuttable={all} onCut={next}/>{all&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="tap-hint">Tap the cake</motion.div>}</motion.section>}
function CakeCelebration({next}){useEffect(()=>{const t=setTimeout(next,2200);return()=>clearTimeout(t)},[next]);return <motion.section className="stage celebration" {...fade}><div className="burst">{Array.from({length:28},(_,i)=><motion.i key={i} style={{'--a':`${i*13}deg`,'--d':`${70+(i%7)*18}px`}} initial={{x:0,y:0,scale:0}} animate={{x:`calc(cos(var(--a)) * var(--d))`,y:`calc(sin(var(--a)) * var(--d))`,opacity:0,scale:1}} transition={{duration:1.1,delay:i*.012}}>{i%3===0?'♥':i%3===1?'✦':'•'}</motion.i>)}</div><div className="celebration-icon"><CakeIcon/></div><h2>Wish made! 💗</h2><p>May it find its way to you.</p></motion.section>}
function CakeIcon(){return <div className="mini-cake"><div/><div/><span>✦</span><span>✦</span><span>✦</span></div>}
function MemoryGallery({next}){const [selected,setSelected]=useState(null);const [broken,setBroken]=useState({});return <motion.section className="stage" {...fade}><span className="eyebrow">KEPT CLOSE</span><h2>Little moments</h2><p className="sub">Some memories deserve their own little place.</p><div className="memory-stack">{config.memories.map((m,i)=><motion.button key={i} className={`memory-card m${i}`} whileTap={{scale:.98}} onClick={()=>setSelected(i)}><div className="photo" style={broken[i]?{background:`linear-gradient(135deg,hsl(${340+i*20} 55% 90%),hsl(${260+i*15} 55% 92%))`}:undefined}><img src={m.image} alt={m.caption} loading="lazy" onError={()=>setBroken(b=>({...b,[i]:true}))}/>{broken[i]&&<span className="fallback">a little memory ♡</span>}</div><span>{m.caption}</span></motion.button>)}</div><Button onClick={next}>Continue <ArrowRight size={18}/></Button>{selected!==null&&<MemoryLightbox index={selected} close={()=>setSelected(null)}/>}</motion.section>}
function MemoryLightbox({index,close}){const m=config.memories[index];return <motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button className="close" onClick={close} aria-label="Close memory"><X/></button><div className="light-photo"><img src={m.image} alt={m.caption}/></div><p>{m.caption}</p></motion.div>}
function WishCards({next}){const [opened,setOpened]=useState([]);const done=opened.length===config.wishes.length;return <motion.section className="stage" {...fade}><span className="eyebrow">THREE LITTLE WISHES</span><h2>A few wishes for you</h2><p className="sub">Tap each card. There is a little thought inside.</p><div className="wish-list">{config.wishes.map((w,i)=><motion.button key={i} className={`wish ${opened.includes(i)?'open':''}`} onClick={()=>setOpened(a=>a.includes(i)?a:[...a,i])} initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:i*.12}}><div className="wish-front"><span>0{i+1}</span><strong>{w.title}</strong><Heart size={17}/></div><AnimatePresence>{opened.includes(i)&&<motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}>{w.message}</motion.p>}</AnimatePresence></motion.button>)}</div>{done?<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><Button onClick={next}>One last thing... <ArrowRight size={18}/></Button></motion.div>:<div className="locked">Open all three to continue</div>}</motion.section>}
function Letter({next}){const paras=config.letter.text.trim().split(/\n\s*\n/);return <motion.section className="stage" {...fade}><div className="letter"><span className="eyebrow">PRIVATE LETTER</span><h2>{config.letter.title}</h2>{paras.map((p,i)=><motion.p key={i} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.25+i*.28}}>{p}</motion.p>)}<div className="signature"><span>With love,</span><strong>{config.senderName}</strong><span>♡</span></div><Button onClick={next}>Read the last surprise <ArrowRight size={18}/></Button></div></motion.section>}
function Final({replay}){return <motion.section className="stage final" {...fade}><Particles celebrate/><div className="final-glow"/><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:1}}><span className="script">for someone wonderful</span><h1>{config.final.title}</h1><div className="name">{config.birthdayName}</div><div className="final-art"><CakeIcon/><div className="orbit o1">♥</div><div className="orbit o2">✦</div><div className="orbit o3">♥</div></div><p>{config.final.message}</p><div className="made">Made with love by {config.senderName}</div><button className="replay" onClick={replay}><RotateCcw size={16}/> Replay the surprise</button></motion.div></motion.section>}
function App(){const [stage,setStage]=useState('intro'),[candles,setCandles]=useState([false,false,false]),[playing,setPlaying]=useState(false);const audio=useRef(null);useEffect(()=>{audio.current=new Audio(config.music);audio.current.loop=true;audio.current.addEventListener('error',()=>setPlaying(false));return()=>audio.current?.pause()},[]);const startMusic=()=>{if(audio.current)audio.current.play().then(()=>setPlaying(true)).catch(()=>{})};const next=()=>setStage(s=>stages[Math.min(stages.indexOf(s)+1,stages.length-1)]);const replay=()=>{audio.current?.pause();if(audio.current)audio.current.currentTime=0;setPlaying(false);setCandles([false,false,false]);setStage('intro');window.scrollTo(0,0)};return <main><Particles/><MusicToggle playing={playing} setPlaying={setPlaying} audio={audio}/>{stage!=='final'&&<Progress stage={stage}/>}<AnimatePresence mode="wait"><div key={stage}>{stage==='intro'&&<Intro next={next} startMusic={startMusic}/>} {stage==='message'&&<Message next={next}/>} {stage==='candles'&&<Candles candles={candles} setCandles={setCandles} next={next}/>} {stage==='cake'&&<CakeCelebration next={next}/>} {stage==='memories'&&<MemoryGallery next={next}/>} {stage==='wishes'&&<WishCards next={next}/>} {stage==='letter'&&<Letter next={next}/>} {stage==='final'&&<Final replay={replay}/>}</div></AnimatePresence></main>}
createRoot(document.getElementById('root')).render(<App/>);
